---
- name: Install Docker, Java, Jenkins, Unzip, and AWS CLI
  hosts: all
  become: true

  tasks:
    - name: Install Java (OpenJDK 17)
      apt:
        name:
          - fontconfig
          - openjdk-17-jre
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages for Docker and unzip
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - unzip
        state: present

    - name: Create the keyrings directory if not exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository to Apt sources
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
        https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
        > /etc/apt/sources.list.d/docker.list
      args:
        executable: /bin/bash

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Verify Docker installation
      command: docker run hello-world
      ignore_errors: true

    - name: Download AWS CLI zip file using curl
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
      args:
        executable: /bin/bash

    - name: Unzip AWS CLI installer
      shell: |
        unzip /tmp/awscliv2.zip -d /tmp/
      args:
        executable: /bin/bash

    - name: Install AWS CLI
      shell: |
        sudo /tmp/aws/install
      args:
        executable: /bin/bash

- name: Install Java, Jenkins, Unzip, and AWS CLI on Jenkins server
  hosts: jenkins
  become: true

  tasks:
    - name: Add Jenkins repository key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins repository to Apt sources
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" \
        > /etc/apt/sources.list.d/jenkins.list
      args:
        executable: /bin/bash

    - name: Update apt cache after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started
